from pathlib import PurePosixPath
from typing import Any

from github import Auth, Github

from lineageai.config import Settings
from lineageai.models import GeneratedModel


class GitHubPublisher:
    def __init__(self, settings: Settings, repository: Any | None = None) -> None:
        if repository is None:
            if not settings.github_token or not settings.github_repository:
                raise ValueError("GITHUB_TOKEN and GITHUB_REPOSITORY are required")
            client = Github(auth=Auth.Token(settings.github_token))
            repository = client.get_repo(settings.github_repository)
        self.repository = repository
        self.base_branch = settings.github_base_branch
        self.models_path = PurePosixPath(settings.github_models_path)

    def publish(self, run_id: str, model: GeneratedModel) -> str:
        branch = f"lineageai/{run_id}"
        owner = self.repository.owner.login
        existing = list(
            self.repository.get_pulls(
                state="all",
                head=f"{owner}:{branch}",
                base=self.base_branch,
            )
        )
        if existing:
            return str(existing[0].html_url)

        try:
            self.repository.get_branch(branch)
        except Exception as error:
            if getattr(error, "status", None) != 404:
                raise
            base_sha = self.repository.get_branch(self.base_branch).commit.sha
            self.repository.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)

        sql_path = str(self.models_path / f"{model.name}.sql")
        schema_path = str(self.models_path / f"{model.name}.yml")
        self._upsert(sql_path, model.sql.rstrip() + "\n", branch, run_id)
        self._upsert(schema_path, model.schema_yml.rstrip() + "\n", branch, run_id)
        pull = self.repository.create_pull(
            title=f"feat(dbt): add {model.name}",
            body=(
                "Generated by LineageAI and validated with dbt + DuckDB.\n\n"
                f"Agent run: `{run_id}`\n\n{model.explanation}"
            ),
            head=branch,
            base=self.base_branch,
        )
        return str(pull.html_url)

    def _upsert(self, path: str, content: str, branch: str, run_id: str) -> None:
        message = f"feat(dbt): generate model for LineageAI run {run_id}"
        try:
            existing: Any = self.repository.get_contents(path, ref=branch)
        except Exception as error:
            if getattr(error, "status", None) != 404:
                raise
            self.repository.create_file(path, message, content, branch=branch)
            return
        self.repository.update_file(
            path,
            message,
            content,
            existing.sha,
            branch=branch,
        )
